baseURL: https://thirsty-meitner-662298.netlify.app/
languageCode: en
title: Blogophonic
author: Hi there
copyright: ''
googleAnalytics: ''
disqusShortname: ''
metaDataFormat: yaml
pygmentsCodeFences: yes
pygmentsOptions: linenos=table
pygmentsStyle: friendly
footnoteReturnLinkContents: '&#8617;'
paginate: 5
preserveTaxonomyNames: yes
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
enableEmoji: yes
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
  tableOfContents:
    endLevel: 2
    ordered: no
    startLevel: 2
params:
  bodyLinkColor: blue
  borderColor: moon-gray
  buttonBgColor: black
  buttonHoverBgColor: blue
  buttonHoverTextColor: white
  buttonTextColor: near-white
  customheadingFontFamily: Fraunces
  customtextFontFamily: Commissioner
  description: A modern, beautiful, and easily configurable blog theme for Hugo.
  favicon: /img/favicon.ico?v=0
  footerTextColor: silver
  headingColor: near-black
  headingFontFamily: sans-serif
  headlineColor: dark-pink
  logo: /img/blogophonic-mark-dark.png
  mainSections:
    - blog
    - project
  navLinkColor: near-black
  navallcaps: yes
  orgLocal: Anywhere
  orgName: RStudio
  sharing_image: /img/papillons.jpg
  show_social_links: yes
  sidebarBgColor: light-gray
  sidebarLinkColor: near-black
  sidebarTextColor: mid-gray
  siteBgColor: near-white
  socialInFooter: yes
  socialInHeader: no
  socialInHome: yes
  textColor: dark-gray
  textFontFamily: sans-serif
  theme: peach
  twitter: apreshill
taxonomies:
  category: categories
  series: series
  tag: tags
menu:
  header:
    - name: About
      title: About Blogophonic
      url: /about/
      weight: 1
    - name: Blog
      title: Blog
      url: /blog/
      weight: 2
    - name: Projects
      title: Project Portfolio
      url: /project/
      weight: 3
